directories:
  output: release
  buildResources: build
appId: com.timekeeper.app
productName: Time Keeper
files:
  - filter:
      - dist/**/*
      - node_modules/**/*
      - package.json
win:
  target: nsis
mac:
  target: dmg
linux:
  target: AppImage
electronVersion: 36.2.0
